//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace universidad_challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjects
    {
        public int id_subject { get; set; }
        public string subject_name { get; set; }
        public int id_teacher { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public int students_max { get; set; }
        public int students { get; set; }
        public string description { get; set; }
    
        public virtual teachers teachers { get; set; }
    }
}
